version: "3.8"

services:
  deepgraph-rag-service:
    container_name: deepgraph-rag-service
    build: .
    ports:
      - "8000:8000"
    # Environment variables for .env usage or direct injection (optional).
    # If you have a .env file, Docker Compose can load them with env_file: .env
    # Or define them inline:
    environment:
      - OLLAMA_API_URL=http://host.docker.internal:11434
      - MODEL=huihui_ai/qwen3-abliterated:1.7b
      - EMBEDDINGS_MODEL=nomic-embed-text:latest
      - CROSS_ENCODER_MODEL=cross-encoder/ms-marco-MiniLM-L-6-v2

    # (Optional) If you want to mount your local code into the container for live development:
    # volumes: 
    #   - ./app:/usr/src/app/app